// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQbq6iLx6qZiR7vzMYaWEeYHo4EmCH5tc',
    appId: '1:973302309115:web:8ea59e6ec7dce70dfe105e',
    messagingSenderId: '973302309115',
    projectId: 'lightore-cd8ff',
    authDomain: 'lightore-cd8ff.firebaseapp.com',
    storageBucket: 'lightore-cd8ff.firebasestorage.app',
    measurementId: 'G-H1S55062PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCigFsFRUITZJxstZ3J2M2Nio6bvzLc6J0',
    appId: '1:973302309115:android:e93c84121d27c1d9fe105e',
    messagingSenderId: '973302309115',
    projectId: 'lightore-cd8ff',
    storageBucket: 'lightore-cd8ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMXWoffkQ6S86IuDqsK6x5dm7yZ0aShCY',
    appId: '1:973302309115:ios:f225ca69ec2b1952fe105e',
    messagingSenderId: '973302309115',
    projectId: 'lightore-cd8ff',
    storageBucket: 'lightore-cd8ff.firebasestorage.app',
    androidClientId: '973302309115-oofhgimnua34uptj7jtg9mvbuh728m08.apps.googleusercontent.com',
    iosClientId: '973302309115-jeovree1s5vo0rlsp1ao0n8h6aaag19n.apps.googleusercontent.com',
    iosBundleId: 'com.example.lightore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMXWoffkQ6S86IuDqsK6x5dm7yZ0aShCY',
    appId: '1:973302309115:ios:f225ca69ec2b1952fe105e',
    messagingSenderId: '973302309115',
    projectId: 'lightore-cd8ff',
    storageBucket: 'lightore-cd8ff.firebasestorage.app',
    androidClientId: '973302309115-oofhgimnua34uptj7jtg9mvbuh728m08.apps.googleusercontent.com',
    iosClientId: '973302309115-jeovree1s5vo0rlsp1ao0n8h6aaag19n.apps.googleusercontent.com',
    iosBundleId: 'com.example.lightore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQbq6iLx6qZiR7vzMYaWEeYHo4EmCH5tc',
    appId: '1:973302309115:web:d48972447a5e8499fe105e',
    messagingSenderId: '973302309115',
    projectId: 'lightore-cd8ff',
    authDomain: 'lightore-cd8ff.firebaseapp.com',
    storageBucket: 'lightore-cd8ff.firebasestorage.app',
    measurementId: 'G-0Y11JFWYJ4',
  );
}
